language: emacs-lisp

dist: trusty
before_install:
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - git clone https://github.com/jwiegley/emacs-async.git $HOME/.async-el

env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-git-snapshot-travis

script:
  - emacs -Q -batch --eval '(message (emacs-version))'
  - emacs -Q -batch -L $HOME/.async-el -L . -l $HOME/.async-el/async.el -l ssh-deploy-test.el

